spring:


  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lab.non_contextual_creation: true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/billingProject
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
